### ISSUE TITLE
Ingest gets an error from Globus Search

### ISSUE THREAD

**Issue by lukaszlacinski** [globus/globus-search-cli#4]
globus-search ingest --source-type gmetalist fails with the error message:

`
Sending batch of size 100
-Start Results-
{"@datatype":"GError","@version":"2017-09-01","code":"BadRequest.ValidationError","error_data":{"messages":{"json":{"source_id":["Unknown field."]}}},"message":"Request failed input validation.","request_id":"dc3acb846e96ef0827a4c32f7a465076","status":400}
`

If `source_id` is removed, https://github.com/globus/globus-search-cli/blob/master/globus_search_cli/commands/ingest.py#L60, the command succeeds.

**Comment by sirosen** [comment]
Just noticed I never closed this. It was fixed at the time of my last comment.
